/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface ArrowsIconProps extends BoxProps {
  size?: number;
}

const ArrowsIcon: React.FC<ArrowsIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <defs></defs>

    <g id="Group_601" data-name="Group 601">
      <path
        id="Path_270"
        data-name="Path 270"
        className="cls-1"
        d="M163.49 182.43l13.84 18.25 13.86-18.25z"
        transform="translate(-163.49 -149.42)"
      />
      <path
        id="Path_345"
        data-name="Path 345"
        className="cls-1"
        d="M191.19 167.67l-13.83-18.25-13.87 18.25z"
        transform="translate(-163.49 -149.42)"
      />
    </g>
  </Box>
);

export default ArrowsIcon;
