/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface BoxIconProps extends BoxProps {
  size?: number;
}

const BoxIcon: React.FC<BoxIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <path
      data-name="Path 250"
      d="M21.44 7.58H8.56a.82.82 0 00-.52.2L3 12.32a.8.8 0 00-.26.58v9.31a1.5 1.5 0 001.5 1.5h21.54a1.5 1.5 0 001.49-1.5V12.9a.79.79 0 00-.25-.58L22 7.78a.82.82 0 00-.56-.2zm4.94 14.63a.61.61 0 01-.61.61H4.23a.61.61 0 01-.61-.61v-8.48h6.23a5.18 5.18 0 0010.3 0h6.23zm-7.07-9.37v.26a4.43 4.43 0 01-3.88 4.32 4.3 4.3 0 01-4.71-4.15v-.43H3.85v-.07l4.74-4.29h12.82l4.77 4.29v.07z"
      fill="currentColor"
    />
  </Box>
);

export default BoxIcon;
