/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface CheckmarkIconProps extends BoxProps {
  size?: number;
}

const CheckmarkIcon: React.FC<CheckmarkIconProps> = ({
  size = 30,
  ...props
}) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <path
      d="M11.72 21.49a.58.58 0 01-.4-.17L5.5 15.56a.57.57 0 01.8-.82l5.43 5.37 12-11.55a.58.58 0 01.8.83L12.12 21.32a.56.56 0 01-.4.17z"
      fill="currentColor"
    />
  </Box>
);

export default CheckmarkIcon;
