/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface DotsIconProps extends BoxProps {
  size?: number;
}

const DotsIcon: React.FC<DotsIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <defs />

    <circle className="cls-1" cx={16.29} cy={16.29} r={16.29} />

    <circle className="cls-1" cx={74.86} cy={16.29} r={16.29} />

    <circle className="cls-1" cx={133.43} cy={16.29} r={16.29} />
  </Box>
);

export default DotsIcon;
