/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Flex } from 'theme-ui';

import BoxIcon from './BoxIcon';
import CheckmarkIcon from './CheckmarkIcon';
import DashboardIcon from './DashboardIcon';
import DotsIcon from './DotsIcon';
import EyeIcon from './EyeIcon';
import FolderIcon from './FolderIcon';
import ListIcon from './ListIcon';
import OpenIcon from './OpenIcon';
import PencilIcon from './PencilIcon';
import QuestionIcon from './QuestionIcon';
import RotateIcon from './RotateIcon';
import SettingsIcon from './SettingsIcon';
import ShirtIcon from './ShirtIcon';
import TrashIcon from './TrashIcon';
import UploadIcon from './UploadIcon';

export default {
  title: 'Icons',
};

export const Overview = () => (
  <Flex>
    <BoxIcon />

    <CheckmarkIcon />

    <DashboardIcon />

    <DotsIcon />

    <EyeIcon />

    <FolderIcon />

    <ListIcon />

    <OpenIcon />

    <PencilIcon />

    <QuestionIcon />

    <RotateIcon />

    <SettingsIcon />

    <ShirtIcon />

    <TrashIcon />

    <UploadIcon />
  </Flex>
);

export const Box = () => <BoxIcon />;
export const Checkmark = () => <CheckmarkIcon />;
export const Dashboard = () => <DashboardIcon />;
export const Dots = () => <DotsIcon />;
export const Eye = () => <EyeIcon />;
export const Folder = () => <FolderIcon />;
export const List = () => <ListIcon />;
export const Open = () => <OpenIcon />;
export const Pencil = () => <PencilIcon />;
export const Question = () => <QuestionIcon />;
export const Rotate = () => <RotateIcon />;
export const Settings = () => <SettingsIcon />;
export const Shirt = () => <ShirtIcon />;
export const Trash = () => <TrashIcon />;
export const Upload = () => <UploadIcon />;
