/**
 * do not edit this file. it's autogenerated.
 */

import BoxIcon from './BoxIcon';
import CheckmarkIcon from './CheckmarkIcon';
import DashboardIcon from './DashboardIcon';
import DotsIcon from './DotsIcon';
import EyeIcon from './EyeIcon';
import FolderIcon from './FolderIcon';
import ListIcon from './ListIcon';
import OpenIcon from './OpenIcon';
import PencilIcon from './PencilIcon';
import QuestionIcon from './QuestionIcon';
import RotateIcon from './RotateIcon';
import SettingsIcon from './SettingsIcon';
import ShirtIcon from './ShirtIcon';
import TrashIcon from './TrashIcon';
import UploadIcon from './UploadIcon';

export {
  BoxIcon,
  CheckmarkIcon,
  DashboardIcon,
  DotsIcon,
  EyeIcon,
  FolderIcon,
  ListIcon,
  OpenIcon,
  PencilIcon,
  QuestionIcon,
  RotateIcon,
  SettingsIcon,
  ShirtIcon,
  TrashIcon,
  UploadIcon,
};
