/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface ListIconProps extends BoxProps {
  size?: number;
}

const ListIcon: React.FC<ListIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <path
      data-name="Path 251"
      d="M7.25 10.66A1.25 1.25 0 118.5 9.41a1.25 1.25 0 01-1.25 1.25zm18.09-1.8H9.74V10h15.59zm-18.09 8A1.24 1.24 0 016 15.65a1.25 1.25 0 012.5 0 1.24 1.24 0 01-1.25 1.24zm18.09-1.8H9.74v1.14h15.59zm-18.09 8A1.25 1.25 0 016 21.89a1.27 1.27 0 011.25-1.26 1.25 1.25 0 011.25 1.25 1.25 1.25 0 01-1.25 1.25zm18.09-1.8H9.74v1.11h15.59z"
      fill="currentColor"
      fillRule="evenodd"
    />
  </Box>
);

export default ListIcon;
