/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface OpenIconProps extends BoxProps {
  size?: number;
}

const OpenIcon: React.FC<OpenIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <defs />

    <g id="Group_458" data-name="Group 458">
      <g id="_13" data-name={13}>
        <path
          className="cls-1"
          d="M22.65 25.36H6.84a1.54 1.54 0 01-1.54-1.54V8.27a1.54 1.54 0 011.54-1.54h9.34a.46.46 0 01.46.46.47.47 0 01-.46.46H6.84a.62.62 0 00-.62.62v15.55a.61.61 0 00.62.62h15.81a.62.62 0 00.62-.62V14.2a.46.46 0 01.46-.46.47.47 0 01.46.46v9.62a1.55 1.55 0 01-1.54 1.54z"
          id="Path_311"
          data-name="Path 311"
        />
      </g>
      <g id="_4" data-name={4}>
        <path
          className="cls-1"
          d="M12.94 18.3a.47.47 0 01-.33-.14.46.46 0 010-.65L25.49 4.77a.46.46 0 01.65.65L13.26 18.17a.45.45 0 01-.32.13z"
          id="Line_1"
          data-name="Line 1"
        />
        <path
          className="cls-1"
          d="M19 5.56a.47.47 0 01-.46-.46.46.46 0 01.46-.46h6.84a.46.46 0 01.46.46.47.47 0 01-.46.46z"
          id="Line_2"
          data-name="Line 2"
        />
        <path
          className="cls-1"
          d="M25.82 12.39a.46.46 0 01-.46-.46V5.1a.46.46 0 01.92 0v6.83a.46.46 0 01-.46.46z"
          id="Line_3"
          data-name="Line 3"
        />
      </g>
    </g>
  </Box>
);

export default OpenIcon;
