/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface QuestionIconProps extends BoxProps {
  size?: number;
}

const QuestionIcon: React.FC<QuestionIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <defs></defs>

    <path
      className="cls-1"
      d="M15 5.25a10.4 10.4 0 1010.39 10.4A10.4 10.4 0 0015 5.25zm9.36 10.4A9.36 9.36 0 1115 6.29h.06a9.37 9.37 0 019.3 9.36z"
    />

    <path
      className="cls-1"
      d="M15 21a.83.83 0 00-.58.24.82.82 0 00-.25.59.85.85 0 00.83.82.83.83 0 00.58-.25.86.86 0 00.23-.5v-.11A.81.81 0 0015 21zm.1-11.7h-.16a4.43 4.43 0 00-2 .48 4.9 4.9 0 00-1.66 1.41v.06L12 12v-.07a4.17 4.17 0 011.35-1.16 3.44 3.44 0 011.65-.43 2.77 2.77 0 012 .77 2.64 2.64 0 01.78 2 2.68 2.68 0 01-.72 1.89 2.61 2.61 0 01-1.82.82h-.81v3.5h1.09v-2.49a3.73 3.73 0 002.41-1.2 3.85 3.85 0 00-.14-5.26A4 4 0 0015.1 9.3z"
    />
  </Box>
);

export default QuestionIcon;
