/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface RotateIconProps extends BoxProps {
  size?: number;
}

const RotateIcon: React.FC<RotateIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <path
      d="M7.74 12.11l-2.08 1.82a9.22 9.22 0 012.7-5.59A9.32 9.32 0 0115 5.6a9.4 9.4 0 018.92 6.4.46.46 0 10.87-.29A10.3 10.3 0 0015 4.68a10.27 10.27 0 00-7.29 3 10.15 10.15 0 00-3 6.17L3 11.8l-.69.6 2.79 3.25 3.24-2.85zm20 5.48l-2.84-3.24-3.25 2.84.61.69 2.07-1.81a9.4 9.4 0 01-18.28 1.81.46.46 0 00-.87.29 10.32 10.32 0 0020.07-2l1.8 2.05z"
      fill="currentColor"
    />
  </Box>
);

export default RotateIcon;
