/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface TrashIconProps extends BoxProps {
  size?: number;
}

const TrashIcon: React.FC<TrashIconProps> = ({ size = 30, ...props }) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <path
      data-name="Path 319"
      d="M24.15 6.46h-4.73v-.94a1.94 1.94 0 00-2-1.86h-6a1.92 1.92 0 00-2 1.86v1H4.75a1.2 1.2 0 00-1.24 1.11v2.1a1.22 1.22 0 001.24 1.17H5v13.58a1.92 1.92 0 002 1.86h14.91a1.92 1.92 0 002-1.86V10.9h.26a1.23 1.23 0 001.24-1.17v-2.1a1.21 1.21 0 00-1.26-1.17zM11.46 4.58h6a1 1 0 011 .94v.94h-8v-.94a1 1 0 011-.94zm10.45 20.84H7a1 1 0 01-1-.94V10.9h16.91v13.58a1 1 0 01-1 .94zm2.5-15.69a.25.25 0 01-.26.24H4.75a.25.25 0 01-.26-.24v-2.1a.25.25 0 01.26-.24h19.4a.23.23 0 01.25.24zM14 12.62h1v10.69h-1zm-4.21 0h1v10.69h-1zm8.42 0h1v10.69h-1z"
      fill="currentColor"
    />
  </Box>
);

export default TrashIcon;
