/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Flex } from 'theme-ui';
<% icons.forEach(function(icon){ %>
import <%= icon %>Icon from './<%= icon %>Icon';<% }); %>

export default {
  title: 'Icons',
};

export const Overview = () => (
  <Flex>
  <% icons.forEach(function(icon){ %>
    <<%= icon %>Icon />
  <% }); %>
  </Flex>
);

<% icons.forEach(function(icon){ %>
export const <%= icon %> = () => (
  <<%= icon %>Icon />
);<% }); %>
