/**
 * do not edit this file. it's autogenerated.
 */
<% icons.forEach(function(icon){ %>
import <%= icon %>Icon from './<%= icon %>Icon';<% }); %>

export {
<% icons.forEach(function(icon){ %>
<%= icon %>Icon,
<% }); %>
};
