/**
 * do not edit this file. it's autogenerated.
 */
import React from 'react';
import { Box, BoxProps } from 'theme-ui';

export interface <%= name %>IconProps extends BoxProps {
  size?: number;
}

const <%= name %>Icon: React.FC<<%= name %>IconProps> = ({size = 30, ...props}) => (
  <Box
    as="svg"
    // @ts-expect-error
    xmlns="http://www.w3.org/2000/svg"
    width={size + ''}
    height={size + ''}
    viewBox="0 0 30 30"
    {...props}
  >
    <%- svg %>
  </Box>
)

export default <%= name %>Icon;
